function chapterANEenglish(){

    document.getElementById("headertext").innerHTML = "Emergency Department";

    document.getElementById("p1c1").innerHTML = " <h2> Introduction to Stroke</h2>            Stroke is a serious illness and it can affect you or your family in many ways. <br><br> The goal for the acute management of patients with stroke at A&E is to stabilize the patient and to complete initial evaluation and assessment, including imaging and laboratory studies, within 60 minutes of patient arrival so as to qualify for emergent and time-sensitive treatments such as clot dissolving medication, clot extraction, and surgery. <br><br> Timely treatment and supportive care of the stroke patient in the ED is crucial for patient outcomes.";

    document.getElementById("p2c1").innerHTML = "<h2>What is Stroke?</h2>            <p>A stroke occurs when part of the brain gets damaged because the blood supply is interrupted.</p>               <div style='right:0; left:0; margin: 0 auto; position:inherit; display:-webkit-inline-flex;display:-ms-inline-flex; display:-moz-inline-flex; display:inline-flex; vertical-align:center;'>                <figure>                    <img src='images/istroke.gif' style='width: 160px; left:0%; position:relative;'/>                    <figcaption><button class='btn2 resize' id='iStroke1'></button></figcaption>                </figure>                <figure>                    <img src='images/hstroke.gif' style='width: 160px;left:0%; position:relative;'/>                    <figcaption><button class='btn2 resize' id='hStroke1'></button></figcaption>                    </figure>            </div>";  

    document.getElementById("iStroke1").innerHTML = "Ischaemic Stroke";

    document.getElementById("hStroke1").innerHTML = "Haemorrhagic Stroke";

    document.getElementById("iStrokeBodyLayer3").innerHTML = "<h3>Most strokes are caused by a blockage cutting off the blood supply to the brain. This is called an ischaemic stroke.</h3>                    <h3><u>Causes</u></h3>                    <p style='text-align: left'>A blockage can be caused by a blood clot or cholesterol plaque in an artery in the brain. A blood clot may also come from other places like the heart or arteries in the neck.                        <br><br>                    There are a number of reasons why blockages can form and cause an ischaemic stroke. These include:</p>                    <ul class='addListSpace'>                    <li style='text-align: left'>Atherosclerosis occurs when fatty deposits build up on the inside walls of your arteries. They cause your arteries to become harder and narrower, making them more likely to become blocked. </li>                    <li style='text-align: left'>Small vessel disease is when the tiny blood vessels within your brain become blocked. Deposits collect in the blood vessels, causing them to thicken and become less flexible.</li>                    <li style='text-align: left'>Some heart conditions can cause blood clots to form in your heart, which can then move through your blood stream up into your brain.</li>                    <li style='text-align: left'>Arterial dissection occurs when tears develop in the lining of an artery and allow blood to get between the layers of your artery walls. This can happen for no clear reason or it can happen because of an injury, such as whiplash.</li>                    </ul>";

    document.getElementById("hStrokeBodyLayer3").innerHTML = "<h3>Some strokes are due to bleeding in or around the brain. These are called haemorrhagic strokes.</h3>                    <p style='text-align: left'>Although they are not as common, this kind of stroke can be much more serious than ischaemic strokes, which are caused by a blockage.</p>                    <h3><u>Causes</u></h3>                    <p style='text-align: left'>A haemorrhagic stroke can happen when an artery inside your brain bursts causing bleeding within your brain. This is known as an intracerebral haemorrhage.                        <br><br>                    It can also happen because of bleeding on the surface of your brain. Your brain sits inside a cushion of membranes that protect it from your skull.                        <br><br>                    Between the layers of membrane is a space, which is filled with fluid. If blood vessels near the surface of the brain burst, blood can leak into this space. This is83 known as a subarachnoid haemorrhage.                        <br><br>                    Some of the things that can cause bleeding in and within your brain include:</p>                    <ul class='addListSpace'>                    <li>High blood pressure is the one of the main cause of all strokes. High blood pressure weakens the arteries and makes them more likely to tear. </li>                    <li>Cerebral amyloid angiopathy is a condition where a protein called amyloid builds up inside the blood vessels in the brain. This causes damage and makes your blood vessels more likely to tear. This condition is more common among older people.</li>                    <li>An aneurysm is a weak spot on an artery, where the walls have become thin and weak because they have been stretched. This means that they can easily burst, especially if you have high blood pressure. Some aneurysms are present from birth, but things like smoking, using cocaine and some medical conditions can also make them more likely to develop.</li>                    <li>Anticoagulant medication helps to prevent your blood from clotting. If you have an irregular heartbeat (known as atrial fibrillation) it’s likely that you will be given this type of medication to help reduce your risk of stroke. However, if it is not carefully monitored it can sometimes cause bleeding. </li>                    <li>Drugs, such as cocaine, can irritate blood vessel walls making them weaker and more likely to rupture.</li>                    </ul>";

    document.getElementById("p3c1").innerHTML = "<h2>Time is of the essence for management of stroke patients.</h2> <h2 style='color:red'>(Time is brain)</h2> <img src='images/tickingclock.gif'/>";

    document.getElementById("p4c1").innerHTML = "<h2>Stroke Symptoms</h2>   <br><br>       <div id='strokesymptoms' style='top:-30px; position:relative;'>            <figure style='width:200px;'>                <img src='images/faceweakness.png' style='width:120px;'/><figcaption>Face Weakness</figcaption>            </figure>            <figure style='width:200px; position:relative; top:-30px;'>                <img src='images/armweakness.png' style='width:200px;'/><figcaption>Arm Weakness</figcaption>            </figure>            <figure style='width:200px;'>                <img src='images/slurredspeech.png' style='width:150px;'/><figcaption>Slurred Speech</figcaption>            </figure>            <figure style='width:200px;'>                <img src='images/blurredvision.png' style='width:180px;'/> <figcaption>Blurred Vision</figcaption>            </figure>                      </div>            <div style='width:700px; top:-50px; height:30px; left:0; right:0; margin:0 auto; position:relative;'>                         <a id='pageButton' class='strokeSymptoms btn2 resize' href=' '><img src='images/cameraReelIconW.png' width='15px;'/> What to do (ENG)</a>                <a id='pageButton' class='strokeRecognize btn2 resize' href=''><img src='images/cameraReelIconW.png' width='15px;'/> What to do (CHN)</a>                </div>";

    document.getElementById("p5c1").innerHTML = "<div style='display:-webkit-inline-flex; display: -ms-inline-flex; display: -moz-inline-flex; display:inline-flex; margin-left:100px;' class='displayImgRight addMarginTop' >               <figure style='width:20%;'><figcaption>Radiologist</figcaption><img src='images/radiologist.png' width='100px'/></figure>                <figure style='width:20%;'><figcaption>Doctor</figcaption><img src='images/doctor.png' width='130px'/></figure>                <figure style='width:20%;'><figcaption>Nurse</figcaption><img src='images/nurse.png' width='80px'/></figure>            </div>           <br>        <div style='width:90%; top:1em;'> <h2>Labwork</h2> The patient will undergo CT scan to determine the type of stroke, which will determine the type of treatment he/she will receive.  The doctor will be taking patient history, initiate labwork and assessment using stroke scoring scales. The stroke team will also be activated.</div>";

    document.getElementById("p6c1").innerHTML = "<div id='thromTable' style='width:50%; height:100vh;; float:right; text-align:center;'>                <h2>Changes in outcome after treatment</h2>   （Out of 100 patients, 35 patients will have significant benefit while 3 will be harmed.） <br> <img src='images/populationmap.png' width= 400px;/>        </div>            <h1>Ischaemic Stroke <button class='btn4 mriImageBtn'id='ischaemicMri'><img src='images/RADIOACTIVEICONS/radioactiveIconW_1.png' width='100%' /></button></h1>            <h3>If patient arrives within 3hrs, patient may undergo:</h3>            <a id='pageButton' class='thrombolysis btn3 resize' href=' '><img src='images/cameraReelIconW.png' width='15px;'/><b> Thrombolysis</b>  </a>          or/and             <a id='pageButton' class='thrombectomy btn3 resize' href=' ' ><img src='images/cameraReelIconW.png' width='15px;'/><b> Thrombectomy</b> </a>           if they are suitable to receive treatment. <br> <div id='thromTable' style='width:50%; height:90%; float:right; text-align:center;'>              <br>       For patient who underwent thrombolysis, he/she will be transferred to Intensive Care Unit for close monitoring (up to 24hrs)        <br>  <br>      For patient who are eligible for thrombectomy, he/she will be transferred to other hospistals (e.g Tan Tock Seng Hospital) for the procedure.        </div></div>";

    document.getElementById("p7c1").innerHTML = "<br>            <h1>Haemorrhagic Stroke <button class='btn4 mriImageBtn'id='haemorrhagicMri'><img src='images/RADIOACTIVEICONS/radioactiveIconW_1.png' width='100%' /></button></h1>        <b>Haemorrhagic stroke patients might require surgery and they will be <br>referred under            <span style='color:red'>Department of NEUROSURGERY</span></b><br>";
    
    document.getElementById("b01").innerHTML = "Introduction";
    document.getElementById("b02").innerHTML = "Stroke";
    document.getElementById("b03").innerHTML = "Time";
    document.getElementById("b04").innerHTML = "Symptoms";
    document.getElementById("b05").innerHTML = "Labwork";
    document.getElementById("b06").innerHTML = "Ischaemic";
    document.getElementById("b07").innerHTML = "Haemorrhagic";
    };

function chapterANEchinese(){
    document.getElementById("headertext").innerHTML = "急诊室";

   document.getElementById("p1c1").innerHTML = " <h2>了解中风</h2>            中风是一种严重疾病. 它可以在多方面影响您与你的家人. <br><br> 中风的治疗最注重的是时间. 建议必需在60分钟内稳定病患和完成初步评价. 这包括所需头部扫描和相关的各种测试以便给予适当的治疗.比如 血栓溶解剂, 或进行手术. <br><br> 及时的治疗和家人的支持是病患康复的关键.";

   document.getElementById("p2c1").innerHTML = "<h2>什么是中风?</h2>            <p>當向脑部输送血液的血管（动脈）阻塞或破裂时，就会发生中风。供血不畅会导致脑细胞死亡。</p><div style='right:0; left:0; margin: 0 auto; position:inherit; display:-webkit-inline-flex; display: -ms-inline-flex; display: -moz-inline-flex; display:inline-flex; vertical-align:center;'>                <figure>                    <img src='images/istroke.gif' style='width: 160px; left:0%; position:relative;'/>                    <figcaption><button class='btn2 resize' id='iStroke1'></button></figcaption>                </figure>                <figure>                    <img src='images/hstroke.gif' style='width: 160px;left:0%; position:relative;'/>                    <figcaption><button class='btn2 resize' id='hStroke1'></button></figcaption>                    </figure>            </div>";  

    document.getElementById("iStroke1").innerHTML = "缺血性中风";

    document.getElementById("hStroke1").innerHTML = "出血性中风";

    document.getElementById("iStrokeBodyLayer3").innerHTML = "<h3>當脑部供血被阻塞時就会发生缺血性中风。</h3>                    <h3><u>主要有两种类型：</u></h3>                    <p style='text-align: left'>a. 血栓性中风：是最常見的中风类型。這种中风是因动脈中的血凝塊（血栓） 造成，它阻塞了向脑部的部分供血。這些血凝塊通常在被粥样硬化或血斑损坏的动脈中形成。                        <br><br>                   b. 栓塞性中风：由移动凝塊（栓塞）造成。这些凝塊在身体的其他部位形成（通常 是心脏或颈部），且会阻塞动脈。    ";          

    document.getElementById("hStrokeBodyLayer3").innerHTML = "<h3>當动脈破裂，造成颅內出血時，就會发生出血性 中风。</h3>                    <p style='text-align: left'>出血性 中风 比较罕见,但是却比缺血性中风来的严重.</p>                    <h3><u>主要有两种类型：</u></h3>                    <p style='text-align: left'>a. 脑內出血：发生在大脑內部的出血。                        <br><br>                    b. 蛛网膜下出血：发生在大腦表面、蛛网膜下部位（大脑和颅骨之間）的出血。出血通常是由动脈瘤（从动脈血管壁突起的充血袋狀皮折）造成的，它会造成血管破裂或动脈变形。";

    document.getElementById("p3c1").innerHTML = "<h2>及时的治疗是病患康复的关键.</h2>  <h2 style='color:red'>(时间既是脑)</h2> <img src='images/tickingclock.gif'/>";

    document.getElementById("p4c1").innerHTML = "<h3>征兆和症状</h3>          <div id='strokesymptoms' style='top:-30px; position:relative;'>            <figure style='width:200px;'>                <img src='images/faceweakness.png' style='width:120px;'/><figcaption>面部麻木或者虚弱</figcaption>            </figure>            <figure style='width:200px; position:relative; top:-30px;'>                <img src='images/armweakness.png' style='width:200px;'/><figcaption>手臂或者腿部麻木或者虚弱</figcaption>            </figure>            <figure style='width:200px;'>                <img src='images/slurredspeech.png' style='width:150px;'/><figcaption>意识混乱、说话或者理解能力出现问题</figcaption>            </figure>            <figure style='width:200px;'>                <img src='images/blurredvision.png' style='width:180px;'/> <figcaption>单眼或者双眼视物模糊</figcaption>            </figure>                      </div>            <div style='width:700px; top:-50px; height:30px; left:0; right:0; margin:0 auto; position:relative;'>                         <a id='pageButton' class='strokeSymptoms btn2 resize' href=' '><img src='images/cameraReelIconW.png' width='15px;'/> 该这么办 (英文)</a>                <a id='pageButton' class='strokeRecognize btn2 resize' href=''><img src='images/cameraReelIconW.png' width='15px;'/> 该这么办 (中文)</a>                </div>";

    document.getElementById("p5c1").innerHTML = "<div style='display:-webkit-inline-flex; display: -ms-inline-flex; display: -moz-inline-flex; display:inline-flex; margin-left:100px' class='displayImgRight addMarginTop'>                <figure style='width:20%;'><figcaption>放射学家</figcaption><img src='images/radiologist.png' width='100px'/></figure>                <figure style='width:20%;'><figcaption>医生</figcaption><img src='images/doctor.png' width='130px'/></figure>                <figure style='width:20%;'><figcaption>护士</figcaption><img src='images/nurse.png' width='80px'/></figure>    </div> <br> <div style='width:90%; top:1em;'>  患者将进行CT扫描以确定中风的类型，这将确定他/她将接受的治疗的类型。 医生将使用病史，启动实验室工作和使用中风评分量表进行评估。中风专队也将被启动。</div>";

    document.getElementById("p6c1").innerHTML = "<div id='thromTable' style='width:50%; height:90%; float:right; text-align:center;'>                <table style='margin:0 auto; position:relative; top:50px;border-collapse: collapse;'>                    <tr>                        <th></th>                        <th>  </th>                        <th>  </th>                    </tr>                        </table>   <h2>治疗风险</h2>(100人当中，33人将收益，而3人会产生副作用。)  <br>  <img src='images/populationmap.png' width= 400px;/> </div>            <h1>缺血性中风 <button class='btn4 mriImageBtn'id='ischaemicMri'><img src='images/RADIOACTIVEICONS/radioactiveIconW_1.png' width='100%' /></button></h1>            <h3>如果患者在3小时内到达，患者可能会接受：</h3>          <a id='pageButton' class='thrombolysis btn3 resize' href=' '><img src='images/cameraReelIconW.png' width='15px;'/><b> 溶栓治疗</b>  </a>          /          <a id='pageButton' class='thrombectomy btn3 resize' href=' ' ><img src='images/cameraReelIconW.png' width='15px;'/><b> 血栓切除术</b> </a> ; 如果他们适合接受治疗。 <br><br>            对于接受溶栓治疗的患者，他/她将被转移到重症监护室进行密切监测（长达24小时）.<br> 对于有资格进行血栓切除术的患者，他/她将被转移到陈笃生医院进行手术。        </div>";

    document.getElementById("p7c1").innerHTML = "<br>            <h1>出血性中风 <button class='btn4 mriImageBtn'id='haemorrhagicMri'><img src='images/RADIOACTIVEICONS/radioactiveIconW_1.png' width='100%' /></button></h1>        <b>出血性中风患者可能需要手术. 他们将转移到神经外科</b><br>";
    
    document.getElementById("b01").innerHTML = "了解中风";
    document.getElementById("b02").innerHTML = "中风";
    document.getElementById("b03").innerHTML = "时间";
    document.getElementById("b04").innerHTML = "征兆和症状";
    document.getElementById("b05").innerHTML = "验室工作";
    document.getElementById("b06").innerHTML = "缺血性中风";
    document.getElementById("b07").innerHTML = "出血性中风";
};
