function chapterCHenglish(){

    document.getElementById("headertext").innerHTML = "Rehab at Yishun Community Hospital";

    document.getElementById("p1c1").innerHTML = "A community hospital provides you a conducive environment for you to focus on your rehabilitation needs <br><br> You will normally expect to be discharged home within 3 weeks.   <br><br>  Please approach your social worker/case manager to find out more details about the various community hospitals in Singapore. <br>  <img src='images/CH/Picture1.png' width=600px;/>";


    document.getElementById("p3c1").innerHTML = "<p style='line-height:8px;'>The expected length of stay at the community hospital is roughly <b>3 weeks</b></p> <video id='myVideo' onclick='togglePlay()' controls style='border:2px solid black;' <source src='videos/Yishun%20Community%20Hospital.mp4' type='video/mp4'></video>";

    document.getElementById("p4c1").innerHTML = "<b style='font-size:30px;'>Who will look after me?</b> <br> <b>Multidisciplinary Team</b> <br> <div style='right:0; left:0; bottom:0; margin:0 auto; position:inherit; display:inline-flex; display:-ms-inline-flex; display:-moz-inline-flex; display:-webkit-inline-flex; vertical-align:center;'><figure>  <img src='images/doctor.png' width=95px/> <figcaption>Doctor</figcaption></figure> <figure><img src='images/physiotherapist.png' width=70px/> <figcaption>Physiotherapist</figcaption></figure>   <figure><img src='images/occupationaltherapist.png' width=70px/><figcaption>Occupational Therapist</figcaption></figure>   <figure><img src='images/speechtherapist.png' width=69.5px/><figcaption>Speech Therapist</figcaption></figure> <figure><img src='images/casemanager.png' width=100px;/><figcaption>Case Manager</figcaption></figure> <figure><img src='images/nurse.png' width=57px/><figcaption>Nurse</figcaption></figure>   <figure><img src='images/dietitian.png' width=66px;/><figcaption>Dietitian</figcaption></figure> </div>";

    document.getElementById("p5c1").innerHTML = "  <div id='ptContainer' class='rhbTeamContainer'><div id='ptContent' class='rhbTeamContent'><div id='ptStuff1'><p class='moveWord1'>Physiotherapy in CH</p><p><span><b>Regaining function</b></span> <br> Building on the therapy program you have started in the acute stroke unit, the physiotherapist will assist you to regain as much control of your movements as possible to enable you to move and walk safely.</p> The therapy will mainly focus on: <ul class='addListSpace'> <li>Strength and balance</li><li>Tailored home exercises</li></ul></div><div id='ptStuff2' style='display:none;' > <p class='moveWord1'>Strength and Balance</p> <br><img src='images/CH/chSNB.jpg' width='40%' class='addImgBorder displayImgRight' style='margin:10px;'/> Strengthening and balance exercise programs will be implemented to help you continue to adopt a fitness-oriented lifestyle in your recovery journey after stroke. </div> <div id='ptStuff3' style='display:none;' > <p class='moveWord1'>Tailored Home Exercises</p> <br> Your loved ones may also learn to assist you in maximizing your recovery potential through tailored home exercise programs to meet your needs. </div></div> <div  class='teamDescArrow ptDescArrow'>  <button id='left' class='teamDescElem btn ptDescElem' disabled >Previous</button>  <p class='teamDescElem ptDescNumb' style='background-color:white;font-size:20px;' > 1/3</p><button id='right' class='teamDescElem btn ptDescElem'>Next</button> </div> </div><div style='float:right; border-radius:20px; height:80%; width:30%; text-align:center; padding:10px;'><img src='images/physiotherapist.png' width='80px' style='left:0; right:0; position:relative; margin:0 auto; display:block;'/>Physiotherapist</div>   ";

    document.getElementById("p6c1").innerHTML = " <div id='otContainer' class='rhbTeamContainer' style='border-color:#42f49e'><div id='otContent' class='rhbTeamContent'><div id='otStuff1'><p class='moveWord1'>Occupational Therapy in CH</p><img src='images/CH/chOT_RFDA.jpg' width='60%' class='addImgBorder displayImgRight' style='margin-top:20px; margin-left:6px;'/> <p> <span><b>Regaining functions for daily activities</b></span> <br> The occupational therapist will assist you to regain confidence  and ability in engaging in your basic activities of daily living after stroke. </p>The therapy will mainly focus on: <ul class='addListSpace'><li>Activity of daily living training</li><li>Caregiver training</li><li>Home modifications</li></ul> </div><div id='otStuff2' style='display:none;' ><p class='moveWord1'>Caregiver Training</p> <br> <img src='images/CH/chCGT.jpg' width='50%' class='addImgBorder displayImgRight' style='margin:10px;'/> Caregiver training will be provided to teach caregivers:<ul class='addListSpace'> <li>How to assist you in basic activities of daily living (e.g dressing, showering).</li><li>Car transfer. </li></ul> </div> <div id='otStuff3' style='display:none;' > <img src='images/CH/chHM.jpg' width='34%' class='addImgBorder displayImgRight' style='margin:10px;'/> <p class='moveWord1'>Home Modifications</p> <br> Before going home, the occupational therapists (OTs) may: <ul class='addListSpace'><li>Conduct home visits and provide recommendations for home modifications.</li><li>Recommend assistive equipment (e.g wheelchair, <button class='easeLabel' id='easeBtn' style='background-color:lightgreen; font-size:20px; font-family:raleway;'>EASE</button>).</li></ul> </div> </div> <div  class='teamDescArrow otDescArrow'> <button id='left' class='teamDescElem btn otDescElem' disabled >Previous</button> <p class='teamDescElem otDescNumb' style='background-color:white;font-size:20px;' > 1/3</p>  <button id='right' class='teamDescElem btn otDescElem'>Next</button> </div>  </div><div style='float:right; border-radius:20px; height:80%; width:30%; text-align:center; padding:10px;'><img src='images/occupationaltherapist.png' width='80px' style='left:0; right:0; position:relative; margin:0 auto; display:block;'/>Occupational Therapist</div>  ";

    document.getElementById("p7c1").innerHTML = " <div id='sltContainer' class='rhbTeamContainer' style='border-color:#e9b7ff;'> <div id='sltContent' class='rhbTeamContent'>  <div id='sltStuff1'>  <p class='moveWord1'>Speech Therapy in CH</p> <br>  <b>Regaining swallowing and communication functions</b>  <ul class='addListSpace'>  <li>There will be a continuity of care from acute stroke unit in providing therapy to further optimise swallowing and communication abilities.</li> <li>Rehab will be conducted at a higher intensity as prescribed by speech therapist.</li></ul>  </div> <div id='sltStuff2' style='display:none;' > <p class='moveWord1'>Speech Therapy in CH</p> <br><ul class='addListSpace'><li>Strategies may also be recommended to help you cope with the challenges you face in swallowing and communicating.</li> <li>Prior to discharge, caregiver training may also be conducted to yourself and/or caregiver on:  <ul style='list-style-type:circle'><li>Diet and fluid modifications</li><li>Feeding and/or swallowing strategies</li> <li>Swallowing exercises</li> <li>Communication strategies / rehabilitation</li></ul> </li></ul> </div></div><div  class='teamDescArrow sltDescArrow'><button id='left' class='teamDescElem btn sltDescElem' disabled >Previous</button><p class='teamDescElem sltDescNumb' style='background-color:white;font-size:20px;' > 1/2</p><button id='right' class='teamDescElem btn sltDescElem'>Next</button> </div></div> <div style='float:right; border-radius:20px; height:80%; width:30%; text-align:center; padding:10px;'><img src='images/speechtherapist.png' width='80px' style='left:0; right:0; position:relative; margin:0 auto; display:block;'/>Speech Therapist</div>   ";
    
    document.getElementById("p8c1").innerHTML = " <div style='margin:0 auto; width:80%; text-align:center;'><h2>Discharge Care</h2><p>After the patient's stay in the Community Hospital, they would be discharged home.</p></div>   ";
    
    document.getElementById("easeContent1").innerHTML = "<h3 style='text-align: center; width:100%;'>Enhancement for Active Seniors (EASE) by HDB </h3> <ul style='text-align:left; left:0px; display:block; position: absolute; width:45%;'><li>Grab bars within toilet.</li><li>Ramps as appropriate.</li><li>Slip resistant treatment to toilet floors.</li><li><button id='easeVideoButton' class='btn resize' style='border-radius:10px;'>  <img src='images/cameraReelIconW.png' width='15px;'/>Video</button> </li> </ul> <ul style='text-align:left; right:0px; display:block; position: absolute; width:45%; list-style-type:none;'> <li><img class='addImgBorder' src='images/EASE.jpg' width=300px;/></li> </ul>   ";
    
    document.getElementById("b01").innerHTML = "Introduction";
    document.getElementById("b02").innerHTML = "Hospitals";
    document.getElementById("b03").innerHTML = "Rehab-YCH";
    document.getElementById("b04").innerHTML = "Team";
    document.getElementById("b05").innerHTML = "Physiotherapy";
    document.getElementById("b06").innerHTML = "Occupational Therapy";
    document.getElementById("b07").innerHTML = "Speech Therapy";
    document.getElementById("b08").innerHTML = "Discharge Care";
    
};


function chapterCHchinese(){

    document.getElementById("headertext").innerHTML = "义顺社区医院";

    document.getElementById("p1c1").innerHTML = "社区医院为你提供一个有利的环境，使你专注于你的康复需求 <br><br>  住院期大约是3周。   <br><br>  请联系你的社会工作者以了解更多有关新加坡各社区医院的详情。 <br>  <img src='images/CH/Picture1.png' width=600px;/>    ";


    document.getElementById("p3c1").innerHTML = "<p style='line-height:8px;'>在社区医院的预计逗留时间大约是<b>3周</b></p> <video id='myVideo' onclick='togglePlay()' controls style='border:2px solid black;' <source src='videos/Yishun%20Community%20Hospital.mp4' type='video/mp4'></video>    ";

    document.getElementById("p4c1").innerHTML = "<b style='font-size:30px;'>谁会照顾我？</b> <br>  <b>多学科团队</b> <br>  <div style='right:0; left:0; bottom:0; margin:0 auto; position:inherit; display:inline-flex; display:-ms-inline-flex; display:-moz-inline-flex; display:-webkit-inline-flex; vertical-align:center;'> <figure><img src='images/doctor.png' width=95px/> <figcaption>医生</figcaption></figure>  <figure><img src='images/physiotherapist.png' width=70px/><figcaption>生理治疗师</figcaption></figure>               <figure><img src='images/occupationaltherapist.png' width=70px/><figcaption>职业治疗师</figcaption></figure>    <figure><img src='images/speechtherapist.png' width=69.5px/><figcaption>语言治疗师</figcaption></figure>  <figure><img src='images/casemanager.png' width=100px;/><figcaption>病案管理员</figcaption></figure>     <figure><img src='images/nurse.png' width=57px/><figcaption>护士</figcaption></figure>  <figure><img src='images/dietitian.png' width=66px;/><figcaption>营养师</figcaption></figure></div>   ";

    document.getElementById("p5c1").innerHTML = " <div id='ptContainer' class='rhbTeamContainer'><div id='ptContent' class='rhbTeamContent'><div id='ptStuff1'><p class='moveWord1'>物理治疗</p><p><span><b>恢复功能</b></span> <br> 基于你已经在中风专科部开始的治疗计划，物理治疗师将帮助你重新获得尽可能多的控制你的运动，使你能够安全地移动和行走。</p>  治疗将主要集中在：<ul class='addListSpace'><li>力量和平衡</li><li>量身定制的家庭练习</li></ul></div> <div id='ptStuff2' style='display:none;' ><p class='moveWord1'>力量和平衡</p> <br> <img src='images/CH/chSNB.jpg' width='40%' class='addImgBorder displayImgRight' style='margin:10px;'/> 加强和平衡运动计划将实施，以帮助你继续采取健康导向的生活方式在你的恢复旅程中风后。 </div> <div id='ptStuff3' style='display:none;' > <p class='moveWord1'>量身定制家庭锻炼</p> <br> 你的亲人也可以通过量身定制的家庭锻炼计划来帮助你提高恢复潜力。</div></div> <div  class='teamDescArrow ptDescArrow'><button id='left' class='teamDescElem btn ptDescElem' disabled >Previous</button><p class='teamDescElem ptDescNumb' style='background-color:white;font-size:20px;' > 1/3</p><button id='right' class='teamDescElem btn ptDescElem'>Next</button> </div></div>   <div style='float:right; border-radius:20px; height:80%; width:30%; text-align:center; padding:10px;'><img src='images/physiotherapist.png' width='80px' style='left:0; right:0; position:relative; margin:0 auto; display:block;'/>生理治疗师</div> ";

    document.getElementById("p6c1").innerHTML = " <div id='otContainer' class='rhbTeamContainer' style='border-color:#42f49e'>  <div id='otContent' class='rhbTeamContent'><div id='otStuff1'>  <p class='moveWord1'>职业治疗</p>  <img src='images/CH/chOT_RFDA.jpg' width='60%' class='addImgBorder displayImgRight' style='margin-top:20px; margin-left:6px;'/>   <p>  <span> <b>恢复日常活动的功能</b> </span> <br> 职业治疗师将帮助你恢复信心和能力从事中风后日常生活的基本活动。 </p> 治疗将主要集中在：  <ul class='addListSpace'><li>日常生活训练活动</li><li>照顾者培训</li><li>家庭修改</li></ul></div>    <div id='otStuff2' style='display:none;' ><p class='moveWord1'>护理员培训</p> <br>  <img src='images/CH/chCGT.jpg' width='50%' class='addImgBorder displayImgRight' style='margin:10px;'/>护理员培训教导： <ul class='addListSpace'><li>如何协助你进行日常生活的基本活动（如敷料，淋浴）。</li><li>汽车转移。</li></ul></div><div id='otStuff3' style='display:none;' ><img src='images/CH/chHM.jpg' width='34%' class='addImgBorder displayImgRight' style='margin:10px;'/>  <p class='moveWord1'>家庭修改</p> <br>  在回家之前，职业治疗师可以： <ul class='addListSpace'>  <li>进行家访，并提供家庭修改建议。</li> <li>推荐辅助设备（例如轮椅，<button class='easeLabel' id='easeBtn' style='background-color:lightgreen; font-size:20px; font-family:raleway;'> 建屋局乐龄易 </button>  ）。</li></ul></div></div> <div  class='teamDescArrow otDescArrow'><button id='left' class='teamDescElem btn otDescElem' disabled >Previous</button><p class='teamDescElem otDescNumb' style='background-color:white;font-size:20px;' > 1/3</p><button id='right' class='teamDescElem btn otDescElem'>Next</button></div></div> <div style='float:right; border-radius:20px; height:80%; width:30%; text-align:center; padding:10px;'><img src='images/occupationaltherapist.png' width='80px' style='left:0; right:0; position:relative; margin:0 auto; display:block;'/>职业治疗师</div>  ";

    document.getElementById("p7c1").innerHTML = "                      <div id='sltContainer' class='rhbTeamContainer' style='border-color:#e9b7ff;'><div id='sltContent' class='rhbTeamContent'><div id='sltStuff1'><p class='moveWord1'>语言治疗</p> <br> <b>恢复吞咽和通讯功能</b> <ul class='addListSpace'> <li>连续在中风专科部护理 , 进一步优化  治疗吞咽和沟通能力。</li><li>治疗 师将以更高的强度进行语言治疗 </li></ul></div> <div id='sltStuff2' style='display:none;' ><p class='moveWord1'>语言治疗</p> <br> <ul class='addListSpace'><li>推荐策略以帮助你在吞咽和沟通中面临的挑战。</li><li>在出院前，也可以对你和/或护理员进行培训：<ul style='list-style-type:circle'><li>饮食和流体的改善</li><li>喂养和/或吞咽策略</li> <li>吞咽练习</li> <li>沟通策略/康复</li> </ul></li></ul></div></div> <div  class='teamDescArrow sltDescArrow'><button id='left' class='teamDescElem btn sltDescElem' disabled >Previous</button><p class='teamDescElem sltDescNumb' style='background-color:white;font-size:20px;' > 1/2</p><button id='right' class='teamDescElem btn sltDescElem'>Next</button></div></div> <div style='float:right; border-radius:20px; height:80%; width:30%; text-align:center; padding:10px;'><img src='images/speechtherapist.png' width='80px' style='left:0; right:0; position:relative; margin:0 auto; display:block;'/>语言治疗师</div>   ";
    
    document.getElementById("p8c1").innerHTML = "                       <div style='margin:0 auto; width:80%; text-align:center;'> <h2>出院护理</h2> <p>病人在社区医院后将出院回家。</p></div>   ";
    
    document.getElementById("easeContent1").innerHTML = "               <h3 style='text-align: center; width:100%;'>乐龄易计划</h3><ul style='text-align:left; left:0px; display:block; position: absolute; width:45%;'><li>厕所内的抓杆</li><li>舷梯</li><li>防滑地板</li><li><button id='easeVideoButton' class='btn resize' style='border-radius:10px;'>  <img src='images/cameraReelIconW.png' width='15px;'/> 视频 </button> </li></ul><ul style='text-align:left; right:0px; display:block; position: absolute; width:45%; list-style-type:none;'> <li><img class='addImgBorder' src='images/EASE.jpg' width=300px;/></li></ul>   ";
    
    document.getElementById("b01").innerHTML = "介绍";
    document.getElementById("b02").innerHTML = "医院";
    document.getElementById("b03").innerHTML = "义顺社区医院";
    document.getElementById("b04").innerHTML = "多学科团队";
    document.getElementById("b05").innerHTML = "物理治疗";
    document.getElementById("b06").innerHTML = "职业治疗";
    document.getElementById("b07").innerHTML = "语言治疗";
    document.getElementById("b08").innerHTML = "出院护理";
    
};


