function chapterHOMEenglish(){

    document.getElementById("headertext").innerHTML = "Home Discharge";

    document.getElementById("p1c1").innerHTML = "<div id='hBackground' style='height:97%;width:96%; border-radius:20px;background-color:#f4a461; padding-top:10px;'>                    <div id='hDescriptionBackground' style='height:96%;width:96%; float:right;' >                        <div id='hDescriptionBox' style='background-color:white;border-radius:20px;height:100%;width:96%; padding:2px;' >                            <div id='hDescriptionText' style='height:96%;width:96%;margin:0 auto; text-align:center;'>                                <h3>Rehabilitation after Discharge</h3>                                <p>There are various options to continue your therapy after discharge from the hospital.</p>                                <b>Your rehabilition may continue in the following settings based on your needs or reference:</b><br>                                <ul class='listNeedsSpace' style='display:inline-flex;'>                                <li style='padding-right:30px;'>Home Based-Rehabilitaion</li>                                <li style='padding-right:30px;'>Day Rehabilitation Centre</li>                                <li>KTPH Neuro Outpatient Clinic</li>                                </ul>                            </div>                        </div>                    </div>                             </div>";

    document.getElementById("p2c1").innerHTML = "<img src='images/CH/homeHBR.jpg' style='width:34%; margin:20px;' class='addImgBorder displayImgRight'/>            <div style='background-color:white; height:94%; width:50%;overflow:auto'>                <h3>Home Based Rehabilitation</h3>                <ul class='listNeedsSpace'>                <li>Therapists will schedule visits to your home.</li>                <li>Customised rehabilitation for  home bounded elderly.</li>                   </ul>            </div>";  

    document.getElementById("p3c1").innerHTML = "<img src='images/CH/homeDRC.jpg' class='displayImgRight addImgBorder' style='width:50%; margin-left:10px; margin-top:10px; margin-right:50px;'/>            <div id='dayCentreContent' class='rehabChildrenContent'>                <div class='styleTextLeft'>                    <h3>Day Rehabilitation centre @ YCH</h3>                    <p>At Therapy Services D37, we offers an integrated approach in providing a wide range of centre-based rehabilitation services. These services consist of Physiotherapy and Occupational Therapy targeted at optimising mobility, function, and independence. </p>                    <!--<p>To continue your rehabilitation program, you may be advised by your therapist to attend rehabilitation session at the Day Rehabilitation Centre after discharge from the hospital.</p>-->                </div>            </div>";

    document.getElementById("p4c1").innerHTML = "<img src='images/CH/homeNOC.jpg' class='displayImgRight addImgBorder addMarginTop' style='width:38%; margin-right:10px;'/>            <div id='neuroClinicContent' class='styleTextLeft'>                <h3>Neuro Outpatient Clinic @ KTPH</h3>                <p>An outpatient assessment, consultation and therapy will be conducted in a clinic setting. Frequency of visits vary (depending on therapists' recommendation).</p>                   Targeted patient groups:                 <ul>                    <li>those with higher function needs (e.g balancing and memory).                    </li>                    <li>those with specific impairments (e.g hand/leg weakness).                    </li>                </ul>            </div>";
    
    document.getElementById("b01").innerHTML ="Introduction";
    document.getElementById("b02").innerHTML ="Home Based Rehab";
    document.getElementById("b03").innerHTML ="Day Rehab Centre";
    document.getElementById("b04").innerHTML ="Neuro Outpatient Clinic";
};

function chapterHOMEchinese(){
    document.getElementById("headertext").innerHTML = "家";

    document.getElementById("p1c1").innerHTML = "<div id='hBackground' style='height:97%;width:96%; border-radius:20px;background-color:#f4a461; padding-top:10px;'>                    <div id='hDescriptionBackground' style='height:96%;width:96%; float:right;' >                        <div id='hDescriptionBox' style='background-color:white;border-radius:20px;height:100%;width:96%; padding:2px;' >                            <div id='hDescriptionText' style='height:96%;width:96%;margin:0 auto; text-align:center;'>                                <h3>治疗途径</h3>                                <p>在从医院出院后，有多种选择可以继续治疗。</p>                                <b>您的康复可以根据您的需要或参考在以下设置中继续：</b><br>                                <ul class='listNeedsSpace' style='display:inline-flex;'>                                <li style='padding-right:30px;'>家庭式复建</li>                                <li style='padding-right:30px;'>日间康复中心</li>                                <li>邱德拔医院神经学诊所</li>                                </ul>                            </div>                        </div>                    </div>                             </div>";

    document.getElementById("p2c1").innerHTML = "<img src='images/CH/homeHBR.jpg' style='width:34%; margin:20px;' class='addImgBorder displayImgRight'/>            <div style='background-color:white; height:94%; width:50%;overflow:auto'>                <h3>家庭式复建</h3>                <ul class='listNeedsSpace'>                <li>治疗师将安排家访.</li>                <li>为患者提供 家庭式定制康复.</li>                   </ul>            </div>";  

    document.getElementById("p3c1").innerHTML = "<img src='images/CH/homeDRC.jpg' class='displayImgRight addImgBorder' style='width:50%; margin-left:10px; margin-top:10px; margin-right:50px;'/>            <div id='dayCentreContent' class='rehabChildrenContent'>                <div class='styleTextLeft'>                    <h3>•日间康复中心 @ 义顺社区医院</h3>                    <p>在治疗服务D37，我们提供一个综合的方法，提供广泛的基于中心的康复服务。 这些服务包括针对优化移动性，功能和独立性的物理治疗和职业治疗。 </p>                    <!--<p>To continue your rehabilitation program, you may be advised by your therapist to attend rehabilitation session at the Day Rehabilitation Centre after discharge from the hospital.</p>-->                </div>            </div>";

    document.getElementById("p4c1").innerHTML = "<img src='images/CH/homeNOC.jpg' class='displayImgRight addImgBorder addMarginTop' style='width:38%; margin-right:10px;'/>            <div id='neuroClinicContent' class='styleTextLeft'>                <h3>邱德拔医院神经学诊所</h3>                <p>门诊评估，咨询和治疗将在诊所进行。 访率将取决于治疗师的建议。</p>                   目标患者组：                 <ul>                    <li>那些具有更高功能需求（例如平衡和记忆）。                    </li>                    <li>具有特定障碍（例如手/腿无力）。                    </li>                </ul>            </div>";
    
     document.getElementById("b01").innerHTML ="网站介绍";
    document.getElementById("b02").innerHTML ="家庭式复建";
    document.getElementById("b03").innerHTML ="日间康复中心 ";
    document.getElementById("b04").innerHTML ="邱德拔医院神经学诊所";
};
