function journeymapEnglish(){
        document.getElementById("map").innerHTML = "<div class='tabfont'>Journey Map</div>";

        document.getElementById("journeymapback").innerHTML =  "           <div id='journeymap'>                <div id= 'jmfont'><span class='jmCloseButton'><img src='images/close-button.png' width='60%' /></span> JOURNEY  <br> MAP </div>                <div id='journeymapmain'>                    <img id='mapbg' src='images/mapdirections1.png'/>                    <a href='ANE.html' class='labels'id='ane'>                        <div class='daylabel'>Day 1</div>                        <div class='stationlabel' style='background-color:lightsalmon'>Emergency Department</div>                       <img class='ane' class='mapicon' src='images/JourneyMap/ane1.png' /></a>                    <a href='ICU.html' class='labels' id='icu' style='margin-top:-50px; margin-left: 10px;'>                        <div class='daylabel'>Day 1-2</div>                        <div class='stationlabel' style='background-color:lightgoldenrodyellow'>Intensive Care Unit</div>                    <img class='icu' class='mapicon' src='images/JourneyMap/ward1.png' /></a>                    <a href='ASU.html' class='labels'id='asu' style='margin-top:60px; margin-left: -50px;'>                        <div class='daylabel'>Day 3-5</div>                        <div class='stationlabel' style='background-color:lavender'>Acute Stroke Unit</div><img class='asu' class='mapicon' src='images/JourneyMap/postopconservative.png' /></a>                     <a href='CH.html' class='labels'id='ch' style='margin-top:-20px; margin-left: -30px;'>                        <div class='daylabel'>Day 5-8</div>                        <div class='stationlabel' style='background-color:orange'>Community Hospital</div><img class='ch' class='mapicon' src='images/JourneyMap/rehab1.png' /></a>                    <a href='HOME.html' class='labels'id='home' style='margin-top:-50px; margin-left: 5px;'>                        <div class='daylabel'>Day 5-8</div>                        <div class='stationlabel' style='background-color:lightgreen'>Home</div><img class='home' class='mapicon' src='images/JourneyMap/discharge1.png' /></a>                    <a href='resources.html' class='labels' id='resources'>Resources</a>                </div>                    ";
        var mapBtnElem = document.getElementById("mapbtn");
        if (mapBtnElem != null){
            mapBtnElem.innerHTML = "<div class='mapfont'>Back to Journey Map</div>";
        }
        
    };
function journeymapChinese(){
        document.getElementById("map").innerHTML = "<div class='tabfont'>行程知识地图</div>";

        document.getElementById("journeymapback").innerHTML =  "           <div id='journeymap'>                <div id= 'jmfont'><span class='jmCloseButton'><img src='images/close-button.png' width='60%' /></span> 行程知识地图 </div>                <div id='journeymapmain'>                    <img id='mapbg' src='images/mapdirections1.png'/>                    <a href='ANE.html' class='labels'id='ane'>                        <div class='daylabel'>第一天</div>                        <div class='stationlabel' style='background-color:lightsalmon'>急诊室</div>                       <img class='ane' class='mapicon' src='images/JourneyMap/ane1.png' /></a>                    <a href='ICU.html' class='labels' id='icu' style='margin-top:-50px; margin-left: 10px;'>                        <div class='daylabel'>第一至二天</div>                        <div class='stationlabel' style='background-color:lightgoldenrodyellow'>重症监护室</div>                    <img class='icu' class='mapicon' src='images/JourneyMap/ward1.png' /></a>                    <a href='ASU.html' class='labels'id='asu' style='margin-top:60px; margin-left: -50px;'>                        <div class='daylabel'> 第三至五天</div>                        <div class='stationlabel' style='background-color:lavender'>中风专科部</div><img class='asu' class='mapicon' src='images/JourneyMap/postopconservative.png' /></a>                     <a href='CH.html' class='labels'id='ch' style='margin-top:-20px; margin-left: -30px;'>                        <div class='daylabel'>第五至八天</div>                        <div class='stationlabel' style='background-color:orange'>社区医院</div><img class='ch' class='mapicon' src='images/JourneyMap/rehab1.png' /></a>                    <a href='HOME.html' class='labels'id='home' style='margin-top:-50px; margin-left: 5px;'>                        <div class='daylabel'>第五至八天</div>                        <div class='stationlabel' style='background-color:lightgreen'>家</div><img class='home' class='mapicon' src='images/JourneyMap/discharge1.png' /></a>                    <a href='resources.html' class='labels' id='resources'>资源</a>                </div>                    ";
        
        var mapBtnElem = document.getElementById("mapbtn");
        if (mapBtnElem != null){
            mapBtnElem.innerHTML =  "<div class='mapfont'>行程知识地图</div>";
        }
};